/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'priyaagg' at '12/11/18 10:42 AM' with Gradle 2.14.1
 *
 * @author priyaagg, @date 12/11/18 10:42 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
